### PR TITLE
Add project-wide devcontainer

### LINKED ISSUE #6: Add devcontainer for all services
Configure devcontainers for the monorepository structure: when developers open the project with VSCode, it should start all the services automatically

- Follow the https://containers.dev/ specification
- Because VSCode is not able to open and connect to multiple devcontainers simultaneously, we cannot use workspaces.
- Opening the entire repository folder may be awkward for some tools: for instance the VSCode Prettier plugin expects .prettierrc to be at the root, and does not play well with an environment with subprojects.
- The devcontainer will work as follows: opening any of the subproject should launch a top-level docker-compose. However, each devcontainer definition is local to its subproject. This allows different parts of the project to have completely different container and editor settings.

Todo:
- [ ] It is possible to connect to multiple containers through the remote extensions panel, right-click on a container and connect, this opens in a new VSCode window. Check if closing any of these windows shuts down the entire stack while previous windows are still open.

### PR DESCRIPTION
**Pull request by mochiruntime**
Adds devcontainer and docker compose definitions to automatically start the stack in development mode

Closes #6

### CODE REVIEW

**Review by Voxanimus — APPROVED** [review]

**Review by Robb-Fr — APPROVED** [review]

**Comment by Robb-Fr** [comment]
J'adore

**Comment by Robb-Fr** [comment]
Belle PR

**Review by Lumycea — APPROVED** [review]

**Comment by Robb-Fr** [comment]
I love it

**Comment by Robb-Fr** [comment]
Sweet PR

**Review by NoeTerrier — APPROVED** [review]

**Comment by DeepGreen1** [comment]
LGTM

**Pull request merged**
